export enum Channels {
  CLOUD_SYNC = 'cloud-sync',
  LOAD_KEYS = 'load-keys',
  ADD_KEY = 'add-new-key',
  DELETE_KEY = 'delete-key',
  DELETE_GROUP = 'delete-group',
  ADD_GROUP = 'add-group',
  LOGIN = 'start-google-login',
  LOGIN_PASSWORD_VERIFY = 'password-verify',
  LOGIN_SUCCESS = 'login-success',
  REGISTER = 'password-register',
  GET_SESSION = 'get-session',
  SYNCHRONIZING = 'cloud-synchronizing',
  PASSWORD_VERIFY = 'password-verify',
  LOGOUT = 'log-out',
  ERASE_MASTER_PASSWORD = 'erase-master-password',
}
