name: Build and Upload Snap
on:
  push:
    branches:
      - master
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
      - name: Install dependencies
        run: npm run ci
      - name: Build project
        run: npm run package
      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Set Snapcraft credentials
        run: |
          echo "${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}" > snapcraft.login
      - name: Upload Snap to Snap Store
        run: |
          snapcraft login --with snapcraft.login
          snapcraft upload release/build/*.snap --release=stable
