name: Build and Upload Snap
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Export environment variables
        run: |
          echo "ENCRYPTION_KEY=${{ vars.ENCRYPTION_KEY }}" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm run ci
      - name: Build project
        run: ENCRYPTION_KEY=${{ vars.ENCRYPTION_KEY }} npm run package
      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Upload Snap to Snap Store
        run: |
          export SNAPCRAFT_STORE_CREDENTIALS="${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}"
          snapcraft upload release/build/*.snap --release=stable
