name: Build and Upload Snap
on:
  push:
    branches:
      - master
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Set environment variables
        run: |
          echo "GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ vars.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ vars.GOOGLE_REDIRECT_URI }}" >> .env
          echo "ENCRYPTION_KEY=${{ vars.ENCRYPTION_KEY }}" >> .env
      - name: Install dependencies
        run: npm run ci
      - name: Build project
        run: npm run package
      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Upload Snap to Snap Store
        run: |
          export SNAPCRAFT_STORE_CREDENTIALS="${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}"
          snapcraft upload release/build/*.snap --release=stable
